### ISSUE TITLE
只能是mac吗？ win 10 可以吗？

### ISSUE THREAD

**Issue by youngchen1987** [CatchZeng/AppThinning#2]
只能是mac吗？ win 10 可以吗？

**Comment by CatchZeng** [comment]
桌面端暂时只支持 mac，win10 可以先用命令行工具

**Comment by CatchZeng** [comment]
@youngchen1987  已经将桌面端的源代码开源了 https://github.com/CatchZeng/AppThinning-Desktop ，可以用源代码构建出各个平台的安装包，包括 win10 的。
